"""
orchestrator_graph.py — v4 (LangGraph multi-agent with confirmation)
─────────────────────────────────────────────────────────────────────
Pipeline:

   ┌─────────────┐
   │ perception  │  (only when a frame is provided)
   └──────┬──────┘
          ↓
   after_perception ─── danger      → danger_node      → action_speak → END
                  ├──── awaiting_cf → confirm_node     → action_speak → END
                  ├──── needs_clar  → clarify_node     → action_speak → END
                  └──── route_intent
                            │
                            ├── env_action+find → find_object   → action_speak → END
                            ├── env_action      → describe      → action_speak → END
                            ├── navigate        → navigate      → action_speak → END
                            └── query           → query         → action_speak → END

KEY DIFFERENCES vs v3:
  • New `confirm_node` reads the pending question generated by
    DialogueAgent and speaks it BEFORE any camera/navigation
    screen opens.  The user must answer "yes" to proceed.
  • Vision uses free OpenRouter models with fallback
    (gemma-3-27b → nemotron-nano-12b VL).
  • Navigation uses free Overpass + Nominatim + OSRM.
  • Find-object now relies on PerceptionAgent's temporal consensus
    so transient bad frames don't trigger premature "I cannot see".
"""

from __future__ import annotations

import base64
from typing import TypedDict, Optional, Literal

import numpy as np
import cv2

from langgraph.graph import StateGraph, END

from agents.PerceptionAgent import PerceptionAgent
from agents.ActionAgent     import ActionAgent
from agents.Navigateagent   import NavigateAgent
from config import (VLM_MODEL_VISION, VLM_MODEL_FALLBACK, VLM_MODEL_EXTRA_FALLBACKS,
                    VISION_MIN_CONFIRMATIONS, VISION_MAX_HISTORY)
from phrasebook import (t, turn_phrase, distance_phrase, position_word,
                        join_list, env_word, scene_type_word)
from memory_service import (save_sighting, get_last_sighting, reverse_geocode,
                             relative_time, get_personal_object, save_personal_object,
                             get_named_location)


# ═══════════════════════════════════════════════════════════════
# STATE
# ═══════════════════════════════════════════════════════════════

class GlassesState(TypedDict, total=False):
    intent:                 str
    entities:               list[str]
    language:               str
    transcription:          str
    frame_b64:              Optional[str]
    needs_clarification:    bool
    clarification_question: str
    awaiting_confirmation:  bool

    user_lat: Optional[float]
    user_lng: Optional[float]

    scene:        Optional[dict]
    danger_level: str

    mode:        str
    find_target: Optional[str]
    found:       Optional[bool]
    direction:   Optional[str]

    nav_destination: Optional[str]
    nav_mode:        Optional[str]
    nav_update:      Optional[dict]

    speak:        str
    interrupt:    bool
    rate_limited: bool

    # Emotion detection results — populated by perception_node only
    # when mode == DESCRIBE.  Each entry: {label, confidence,
    # position, bbox}.  Empty list if EmotionAgent disabled or no
    # faces detected.
    emotions:     list

    # Memory query target — set by route_intent when intent==memory_query
    memory_target: Optional[str]

    # Device UUID forwarded from X-User-ID header — scopes all DB reads/writes
    user_id: Optional[str]

    # Set to True by main.py when user confirmed a duplicate-replace prompt,
    # so save_location_node skips the duplicate check and overwrites directly.
    _force_replace: Optional[bool]


# ═══════════════════════════════════════════════════════════════
# NODE 1 — perception (only when frame exists)
# ═══════════════════════════════════════════════════════════════

def perception_node(state: GlassesState, *,
                    perception: PerceptionAgent,
                    emotion=None) -> GlassesState:
    frame_b64   = state.get("frame_b64")
    find_target = state.get("find_target")
    mode        = state.get("mode", "")

    if not frame_b64:
        return {**state, "scene": None, "danger_level": "LOW",
                "rate_limited": False, "emotions": []}

    rate_limited = False
    emotions: list = []
    try:
        raw_bytes = base64.b64decode(frame_b64)
        arr       = np.frombuffer(raw_bytes, dtype=np.uint8)
        frame     = cv2.imdecode(arr, cv2.IMREAD_COLOR)
        if frame is None:
            print("[perception] imdecode None")
            return {**state, "scene": None, "danger_level": "LOW",
                    "rate_limited": False, "emotions": []}

        frame_small = cv2.resize(frame, (perception.width, perception.height))
        img_b64     = perception.encode(frame_small)
        raw         = perception.ask(img_b64, find_target=find_target)
        if raw is None:
            # All VLM models exhausted — tell the frontend to back off
            rate_limited = True
            print("[perception] all models exhausted — rate_limited=True")
        scene = perception.parse_output(raw, find_target=find_target) if raw else None
        if scene and find_target:
            scene = perception.apply_consensus(scene, find_target)

        # Emotion inference — run when the user asked to describe the
        # scene (intent == env_action with no find-type keywords).
        # NOTE: `mode` is still "IDLE" here because route_intent hasn't
        # run yet — we must infer describe intent from `intent` +
        # transcription instead of relying on mode == "DESCRIBE".
        _transcript_lc = state.get("transcription", "").lower()
        _find_kws = ["find", "where is", "where's", "look for",
                     "search", "locate", "lost"]
        _is_describe_intent = (
            state.get("intent") == "env_action"
            and not any(kw in _transcript_lc for kw in _find_kws)
        )
        # Also allow explicit DESCRIBE mode (used by the /vision endpoint)
        _is_describe_intent = _is_describe_intent or mode == "DESCRIBE"

        if _is_describe_intent:
            if emotion is None:
                print("[emotion] skipped — no agent injected")
            elif not emotion.ready:
                print("[emotion] skipped — agent not ready "
                      "(check model file + tensorflow install)")
            else:
                try:
                    emotions = emotion.detect(frame)
                    if emotions:
                        print(f"[emotion] detected: "
                              f"{[(e['label'], round(e['confidence'], 2), e['position']) for e in emotions]}")
                    else:
                        print("[emotion] no faces detected in this frame")
                except Exception as e:
                    print(f"[emotion] error (non-fatal): {e}")
                    emotions = []

        # ── Personal person identification (all modes) ───────────
        # Runs whenever the scene contains a person-like object and the
        # user has saved contacts (including themselves with rel="self").
        _person_labels = frozenset({
            "person", "man", "woman", "child", "human", "face", "people",
            "boy", "girl", "figure",
        })
        _scene_objs = (scene.get("objects", []) if scene else [])
        _has_person = any(
            any(pl in o.get("label", "").lower() for pl in _person_labels)
            for o in _scene_objs
        )
        if _has_person and scene is not None:
            _uid = state.get("user_id") or ""
            if _uid:
                try:
                    from memory_service import get_all_personal_persons
                    _saved = get_all_personal_persons(_uid)
                    if _saved:
                        _pid = perception.ask_person_id(img_b64, _saved)
                        if _pid and _pid.get("match"):
                            scene["identified_persons"] = [_pid]
                            print(f"[person_id] {_pid['match']} "
                                  f"conf={_pid['confidence']} "
                                  f"pos={_pid['position']}")
                except Exception as _pe:
                    print(f"[person_id] non-fatal: {_pe}")

    except Exception as e:
        print(f"[perception] error: {e}")
        scene = None

    danger_level = scene.get("danger_level", "LOW") if scene else "LOW"
    return {**state, "scene": scene, "danger_level": danger_level,
            "rate_limited": rate_limited, "emotions": emotions}


# ═══════════════════════════════════════════════════════════════
# CONDITIONAL EDGE
# ═══════════════════════════════════════════════════════════════

def after_perception(state: GlassesState) -> Literal[
    "danger_node", "confirm_node", "clarify_node", "route_intent"
]:
    scene = state.get("scene") or {}
    is_dangerous = scene.get("is_dangerous")
    find_target  = state.get("find_target")
    mode         = state.get("mode")

    # DESCRIBE mode: the user explicitly asked "describe what's around
    # me" — they want a description, not a danger alert about their own
    # living room.  Suppress the danger path entirely.  Danger is for
    # the navigation flow, not for static scene description.
    if is_dangerous and mode == "DESCRIBE":
        scene["is_dangerous"]   = False
        scene["danger_level"]   = "LOW"
        scene["danger_message"] = ""
        return "route_intent"

    # If we're actively in FIND mode and the "danger" the VLM is
    # flagging is actually the object the user asked us to find,
    # suppress the danger path so the user hears "I found your X"
    # instead of a hazard warning.
    if is_dangerous and find_target and mode in ("FIND_OBJECT", "FIND"):
        target_lc = find_target.lower()
        objects   = scene.get("objects", []) or []
        threats_match_target = any(
            target_lc in (str(o.get("label", "")).lower()) for o in objects
        )
        if threats_match_target or scene.get("target_found"):
            # The "hazard" is what the user is looking for — not a hazard.
            scene["is_dangerous"]    = False
            scene["danger_level"]    = "LOW"
            scene["danger_message"]  = ""
            scene["consensus_state"] = "FOUND"
            return "route_intent"

    if is_dangerous:
        return "danger_node"
    if state.get("awaiting_confirmation") and state.get("clarification_question"):
        return "confirm_node"
    if state.get("needs_clarification") and state.get("clarification_question"):
        return "clarify_node"
    return "route_intent"


# ═══════════════════════════════════════════════════════════════
# NODE 2 — danger / confirm / clarify
# ═══════════════════════════════════════════════════════════════

def _build_localized_danger(scene: dict, lang: str) -> str:
    """Compose a danger sentence in the user's language from the
    structured scene fields, instead of trusting the VLM's English."""
    cmd = (scene.get("navigation_command") or "GO_FORWARD").upper()
    cmd_phrase = {
        "STOP":       t("danger_stop", lang),
        "MOVE_LEFT":  t("danger_move_left", lang),
        "MOVE_RIGHT": t("danger_move_right", lang),
        "WAIT":       t("danger_wait", lang),
        "GO_FORWARD": t("danger_caution_ahead", lang),
    }.get(cmd, t("danger_caution_ahead", lang))

    # Add up to 2 nearest threat objects with position/distance
    threat_lines = []
    for obj in (scene.get("objects") or []):
        if not obj.get("threat"):
            continue
        if obj.get("distance") not in {"close", "near", "medium"}:
            continue
        line = t("danger_object_position", lang,
                 label=obj.get("label", ""),
                 dist=distance_phrase(obj.get("distance", "near"), lang),
                 position=position_word(obj.get("position", "center"), lang))
        threat_lines.append(line)
        if len(threat_lines) >= 2:
            break

    if threat_lines:
        return cmd_phrase + " " + " ".join(threat_lines)
    return cmd_phrase


def danger_node(state: GlassesState) -> GlassesState:
    scene = state.get("scene") or {}
    lang  = state.get("language", "en")

    # For English the PerceptionAgent's pre-built message is fine.
    # For other languages, compose locally from structured fields so
    # the user actually hears their own language.
    if lang == "en":
        message = (scene.get("danger_message")
                   or scene.get("guidance")
                   or t("danger_caution_ahead", lang))
    else:
        message = _build_localized_danger(scene, lang)

    print(f"[danger] 🚨 ({lang}) {message}")
    return {**state, "speak": message, "interrupt": True}


def confirm_node(state: GlassesState) -> GlassesState:
    """Speak the 'Did you mean X?' question and pause the pipeline."""
    q = state.get("clarification_question", "")
    print(f"[confirm] ❓ {q}")
    return {**state, "speak": q, "interrupt": False, "mode": "AWAIT_CONFIRM"}


def clarify_node(state: GlassesState) -> GlassesState:
    q = state.get("clarification_question", "")
    print(f"[clarify] ❓ {q}")
    return {**state, "speak": q, "interrupt": False, "mode": "IDLE"}


# ═══════════════════════════════════════════════════════════════
# NODE 3 — route_intent
# ═══════════════════════════════════════════════════════════════

def route_intent(state: GlassesState) -> GlassesState:
    intent     = state.get("intent", "unknown")
    entities   = state.get("entities", [])
    transcript = state.get("transcription", "").lower()

    mode        = "IDLE"
    find_target = state.get("find_target")

    def _entity_str(e) -> str:
        """Safely extract a plain string from an entity that may be a
        string or a legacy dict like {'type': 'object', 'value': 'phone'}."""
        if isinstance(e, str):
            return e
        if isinstance(e, dict):
            return str(e.get("value") or e.get("target") or "")
        return str(e)

    if intent == "env_action":
        find_kws = ["find", "where is", "where's", "look for", "search",
                    "locate", "lost", "فين", "دور", "شوفلي", "لقّيلي"]
        if any(k in transcript for k in find_kws) or entities:
            mode        = "FIND_OBJECT"
            find_target = _entity_str(entities[0]) if entities else "object"
        else:
            mode = "DESCRIBE"
    elif intent == "navigate":
        mode = "NAVIGATE"
    elif intent == "query":
        mode = "QUERY"
    elif intent == "read_handwriting":
        mode = "READ_HANDWRITING"
    elif intent == "memory_query":
        mode = "MEMORY_QUERY"
    elif intent == "name_query":
        mode = "NAME_QUERY"
    elif intent == "save_location":
        mode = "SAVE_LOCATION"
    elif intent == "delete_location":
        mode = "DELETE_LOCATION"
    elif intent == "save_object":
        mode = "SAVE_OBJECT"
    elif intent == "save_person":
        mode = "SAVE_PERSON"

    # Enhance find_target with personal object description if saved
    if mode == "FIND_OBJECT" and find_target:
        try:
            _pobj = get_personal_object(find_target, state.get("user_id") or "")
            if _pobj and _pobj.get("description"):
                find_target = f"{find_target} — looks like: {_pobj['description']}"
        except Exception:
            pass

    memory_target = _entity_str(entities[0]) if (intent == "memory_query" and entities) else state.get("memory_target")

    return {**state, "mode": mode, "find_target": find_target, "memory_target": memory_target}


def after_route(state: GlassesState) -> Literal[
    "find_object", "describe", "navigate", "query",
    "read_handwriting", "memory_node", "name_node",
    "save_location_node", "delete_location_node",
    "save_object_node", "save_person_node", "action_speak"
]:
    return {
        "FIND_OBJECT":       "find_object",
        "DESCRIBE":          "describe",
        "NAVIGATE":          "navigate",
        "QUERY":             "query",
        "READ_HANDWRITING":  "read_handwriting",
        "MEMORY_QUERY":      "memory_node",
        "NAME_QUERY":        "name_node",
        "SAVE_LOCATION":     "save_location_node",
        "DELETE_LOCATION":   "delete_location_node",
        "SAVE_OBJECT":       "save_object_node",
        "SAVE_PERSON":       "save_person_node",
    }.get(state.get("mode", "IDLE"), "action_speak")


# ═══════════════════════════════════════════════════════════════
# NODE 4a — find_object (uses temporal consensus)
# ═══════════════════════════════════════════════════════════════

def find_object(state: GlassesState) -> GlassesState:
    target = state.get("find_target") or "object"
    scene  = state.get("scene") or {}
    cstate = scene.get("consensus_state", "SEARCHING")
    lang   = state.get("language", "en")
    rl     = state.get("rate_limited", False)

    # No frame yet → tell user we're opening the camera
    if not state.get("frame_b64"):
        return {**state,
                "speak": t("opening_camera_for_find", lang, target=target),
                "found": False}

    # Backend exhausted its free quota — stay silent (do NOT lie that
    # the camera is unclear).  The frontend will see rate_limited and
    # back off automatically.
    if rl:
        return {**state, "speak": "", "found": False}

    # Bad frame
    if scene.get("confidence") == "LOW" and cstate != "FOUND":
        return {**state,
                "speak": t("searching_camera_unclear", lang),
                "found": False}

    # FOUND (consensus reached)
    if cstate == "FOUND" and scene.get("target_found"):
        pos  = scene.get("target_position", "center")
        dist = scene.get("target_distance", "nearby") or "nearby"
        speak = t("found_target", lang,
                  target=target,
                  turn=turn_phrase(pos, lang),
                  dist=distance_phrase(dist, lang))
        # ── Auto-save to memory (silent, non-blocking) ──────────
        try:
            # Build a rich scene description from all available scene fields
            scene_parts = []
            env_raw   = scene.get("environment", "")
            stype_raw = scene.get("scene_type", "")
            if env_raw and env_raw != "unknown":
                scene_parts.append(env_raw)          # "indoor" / "outdoor"
            if stype_raw and stype_raw != "other":
                scene_parts.append(stype_raw)        # "room" / "desk" / "street"
            # Add nearby objects (excluding the found target itself)
            nearby = [
                o.get("label", "") for o in scene.get("objects", [])[:4]
                if o.get("label", "").lower() != target.lower()
                and o.get("distance") in ("close", "near", "medium")
            ]
            if nearby:
                scene_parts.append("near " + ", ".join(nearby))
            # Fallback to guidance text
            if not scene_parts:
                guidance = scene.get("guidance", "")
                if guidance:
                    scene_parts.append(guidance)
            scene_desc = ". ".join(scene_parts) if scene_parts else ""
            save_sighting(
                name              = target,
                lat               = state.get("user_lat"),
                lng               = state.get("user_lng"),
                scene_description = scene_desc,
                user_id           = state.get("user_id") or "",
            )
        except Exception as _me:
            print(f"[memory] auto-save error (non-fatal): {_me}")
        return {**state, "speak": speak, "found": True, "direction": pos}

    # SEARCHING — silent (don't repeat "still searching")
    if cstate == "SEARCHING":
        return {**state, "speak": "", "found": False}

    # NOT_FOUND after several attempts — give a directional hint
    objects = scene.get("objects", [])
    if objects:
        names = join_list([o["label"] for o in objects[:3]], lang)
        speak = t("cannot_see_with_others", lang, target=target, names=names)
        direction = "right"
    else:
        speak = t("cannot_see_alone", lang, target=target)
        direction = "right"
    return {**state, "speak": speak, "found": False, "direction": direction}


# ═══════════════════════════════════════════════════════════════
# NODE 4b — describe
# ═══════════════════════════════════════════════════════════════

def describe(state: GlassesState) -> GlassesState:
    scene = state.get("scene") or {}
    lang  = state.get("language", "en")
    has_frame = bool(state.get("frame_b64"))

    # No frame yet — this happens when /process is called for the
    # confirmation reply ("yes").  The camera screen is about to open
    # and will send a frame to /vision.  Stay silent so we don't say
    # "I cannot see clearly" right before the real description arrives.
    if not has_frame:
        return {**state, "speak": ""}

    if not scene or scene.get("confidence") == "LOW":
        return {**state, "speak": t("describe_unclear", lang)}

    env_raw    = scene.get("environment", "")
    stype_raw  = scene.get("scene_type", "")
    objects    = scene.get("objects", [])[:4]
    guidance   = scene.get("guidance", "")  # this comes from the VLM in EN
    if guidance and guidance.lstrip().startswith(('{', '[', '`')):
        guidance = ""

    # ── Enrich object labels with personal names from DB ────────
    _uid = state.get("user_id", "")
    if _uid:
        try:
            from memory_service import get_all_personal_objects
            _pers_objs = get_all_personal_objects(_uid)
            if _pers_objs:
                for obj in objects:
                    _lbl_words = set(obj.get("label", "").lower().split())
                    for po in _pers_objs:
                        _po_words = set(po["name"].lower().split())
                        if _lbl_words & _po_words:
                            obj["label"] = f"your {po['name']}"
                            break
        except Exception:
            pass

    parts = [t("object_phrase", lang,
               label=o["label"],
               position=position_word(o["position"], lang),
               dist=distance_phrase(o["distance"], lang))
             for o in objects]
    obj_text = join_list(parts, lang) if parts else t("describe_nothing_notable", lang)

    if env_raw and stype_raw and env_raw != "unknown":
        speak = t("describe_outdoor_indoor", lang,
                  env=env_word(env_raw, lang),
                  scene_type=scene_type_word(stype_raw, lang),
                  objects=obj_text,
                  guidance=guidance)
    else:
        speak = t("describe_simple", lang,
                  objects=obj_text,
                  guidance=guidance)
    speak = speak.strip()

    # ── Append emotion sentence (if any faces were classified) ──
    # We frame emotions cautiously: "looks happy" rather than
    # "is happy" — emotion classification on real-world faces is
    # noisy and a stranger's actual feelings are not ours to assert.
    emotions = state.get("emotions") or []
    if emotions:
        emo_parts = []
        # Cap at 2 most-confident faces to keep the sentence short
        for e in emotions[:2]:
            pos_key = f"face_position_{e['position']}"
            emo_parts.append(t("emotion_face_phrase", lang,
                               emotion=t(f"emotion_{e['label']}", lang),
                               position=t(pos_key, lang)))
        emo_sentence = join_list(emo_parts, lang)
        connector = " " if speak.endswith((".", "!", "?")) else ". "
        speak = speak + connector + emo_sentence
        if not speak.endswith((".", "!", "?")):
            speak += "."

    # ── Append identified-person sentence ───────────────────────
    # Only fires when person_id matched with at least medium confidence.
    _identified = scene.get("identified_persons") or []
    for _ip in _identified:
        if not _ip.get("match") or _ip.get("confidence") == "low":
            continue
        _name = _ip["match"]
        _rel  = (_ip.get("relationship") or "").strip().lower()
        _pos  = (_ip.get("position") or "center").lower()
        _connector = " " if speak.endswith((".", "!", "?")) else ". "

        # Special case: user saved their own face (relationship == "self")
        if _rel in {"self", "me", "myself"}:
            _i_see_you = {
                "en": f"I can see you, {_name}.",
                "fr": f"Je vous vois, {_name}.",
                "ar": f"أراك يا {_name}.",
                "tn": f"نشوفك يا {_name}.",
            }.get(lang, f"I can see you, {_name}.")
            speak = speak + _connector + _i_see_you
            continue

        _rel_prefix = {
            "en": f"{_rel} " if _rel else "",
            "fr": f"{_rel} " if _rel else "",
            "ar": f"({_rel}) " if _rel else "",
            "tn": f"({_rel}) " if _rel else "",
        }
        _rp = _rel_prefix.get(lang, _rel_prefix["en"])
        _person_phrases = {
            "en": {
                "left":   f"Your {_rp}{_name} is on your left.",
                "right":  f"Your {_rp}{_name} is on your right.",
                "center": f"Your {_rp}{_name} is right in front of you.",
            },
            "fr": {
                "left":   f"Votre {_rp}{_name} est à votre gauche.",
                "right":  f"Votre {_rp}{_name} est à votre droite.",
                "center": f"Votre {_rp}{_name} est juste devant vous.",
            },
            "ar": {
                "left":   f"{_name} {_rp}على يسارك.",
                "right":  f"{_name} {_rp}على يمينك.",
                "center": f"{_name} {_rp}أمامك مباشرة.",
            },
            "tn": {
                "left":   f"{_name} {_rp}في اليسار متاعك.",
                "right":  f"{_name} {_rp}في اليمين متاعك.",
                "center": f"{_name} {_rp}قدامك مباشرة.",
            },
        }
        _lang_map = _person_phrases.get(lang, _person_phrases["en"])
        _sentence  = _lang_map.get(_pos, _lang_map["center"])
        speak = speak + _connector + _sentence

    return {**state, "speak": speak}


# ═══════════════════════════════════════════════════════════════
# Reverse geocode helper (for "where am I")
# ═══════════════════════════════════════════════════════════════

def _reverse_geocode(lat: float, lng: float) -> Optional[str]:
    import requests as _req
    try:
        r = _req.get(
            "https://nominatim.openstreetmap.org/reverse",
            params={"lat": lat, "lon": lng, "format": "json"},
            headers={"User-Agent": "BlindGlassesApp/1.0"},
            timeout=8)
        addr = r.json().get("address", {})
        parts = []
        road = (addr.get("road") or addr.get("pedestrian")
                or addr.get("footway"))
        if road:
            parts.append(road)
        area = (addr.get("suburb") or addr.get("neighbourhood")
                or addr.get("city_district") or addr.get("town")
                or addr.get("city") or addr.get("county"))
        if area:
            parts.append(area)
        return ", ".join(parts) if parts else r.json().get("display_name", "")[:60]
    except Exception as e:
        print(f"[navigate] reverse geocode: {e}")
        return None


_LOCATION_PHRASES = [
    "where am i", "where are we", "where is my location",
    "my location", "current location", "show my location",
    "what is my location", "what's my location",
    "find my location", "locate me", "locate myself",
    "where am i right now", "what street", "which street", "what road",
    "show me on the map", "وين أنا", "فين أنا", "موقعي", "أين أنا",
]


# ═══════════════════════════════════════════════════════════════
# NODE 4c — navigate
# ═══════════════════════════════════════════════════════════════

def navigate(state: GlassesState, *, navigator: NavigateAgent) -> GlassesState:
    lat        = state.get("user_lat")
    lng        = state.get("user_lng")
    dest       = state.get("nav_destination")
    mode       = state.get("nav_mode") or "walking"
    lang       = state.get("language", "en")
    transcript = state.get("transcription", "").lower()

    if lat is None or lng is None:
        return {**state, "speak":
                "I need your GPS location to navigate. Please enable location."}

    # "Where am I?"
    if not dest and any(p in transcript for p in _LOCATION_PHRASES):
        area = _reverse_geocode(lat, lng)
        speak = (f"You are at {area}." if area
                 else f"Coordinates {lat:.5f} North, {lng:.5f} East.")
        return {**state, "speak": speak, "nav_update": None}

    # New trip (or different destination)
    if dest and (not navigator.has_active_trip
                 or dest.lower() != navigator.destination_str.lower()):
        # Check if dest is a saved named location — use its GPS directly
        dest_lat = None
        dest_lng = None
        try:
            from memory_service import get_named_location as _get_loc
            _saved = _get_loc(dest, state.get("user_id") or "")
            if _saved:
                dest_lat = _saved["gps_lat"]
                dest_lng = _saved["gps_lng"]
                print(f"[navigate] resolved '{dest}' → {dest_lat},{dest_lng}")
                # Check if user is already at this location (within ~50m)
                if lat is not None and lng is not None:
                    _dlat = abs(dest_lat - lat)
                    _dlng = abs(dest_lng - lng)
                    if _dlat < 0.0005 and _dlng < 0.0005:  # ~50m
                        _already_there = {
                            "en": f"You are already at {dest}.",
                            "fr": f"Vous êtes déjà à {dest}.",
                            "ar": f"أنت بالفعل في {dest}.",
                            "tn": f"انت توا في {dest}.",
                        }
                        return {**state,
                                "speak": _already_there.get(lang, _already_there["en"]),
                                "nav_update": None}
                dest = f"{dest_lat},{dest_lng}"
        except Exception:
            pass
        result = navigator.start_trip(origin_lat=lat, origin_lng=lng,
                                      destination=dest, mode=mode,
                                      language=lang)
        nav_update = {"arrived": False, "off_route": False,
                      "detour_warning": None, "current_step": 0}
        return {**state, "speak": result["speak"],
                "nav_update": nav_update, "direction": "center"}

    # Recalculate
    if "recalculate" in transcript or "reroute" in transcript:
        result = navigator.recalculate(lat, lng)
        return {**state, "speak": result["speak"], "direction": "center"}

    # Regular GPS update
    if navigator.has_active_trip:
        update    = navigator.update_position(lat, lng)
        speak     = update.get("speak", "")
        interrupt = bool(update.get("detour_warning"))
        return {**state, "speak": speak, "interrupt": interrupt,
                "nav_update": update, "direction": "center"}

    return {**state, "speak":
            "Where would you like to go? Say take me to followed by a place."}


# ═══════════════════════════════════════════════════════════════
# NODE 4d — query
# ═══════════════════════════════════════════════════════════════

def query(state: GlassesState) -> GlassesState:
    entities = state.get("entities", [])
    entity   = entities[0] if entities else "that"
    speak    = f"You asked about {entity}. This feature is coming soon."
    return {**state, "speak": speak}


# ═══════════════════════════════════════════════════════════════
# NODE 4e — read_handwriting
# Tells the user to open the handwriting screen. The actual OCR
# happens in handwriting_endpoint.py via the Flutter HandwritingScreen.
# ═══════════════════════════════════════════════════════════════

_READ_HANDWRITING_PROMPT = {
    "en": "Opening handwriting reader. Please point the camera at the text.",
    "fr": "Ouverture du lecteur d'écriture. Pointez la caméra vers le texte.",
    "ar": "جاري فتح قارئ الكتابة. وجّه الكاميرا نحو النص.",
    "tn": "نفتحولك قارئ الكتابة. وجّه الكاميرا ناحية النص.",
}

def read_handwriting_node(state: GlassesState) -> GlassesState:
    lang  = state.get("language", "en")
    speak = _READ_HANDWRITING_PROMPT.get(lang, _READ_HANDWRITING_PROMPT["en"])
    return {**state, "speak": speak, "mode": "READ_HANDWRITING"}


# ═══════════════════════════════════════════════════════════════
# NODE 4f — memory_node
# Answers "where did I last see my X?" from the SQLite memory DB.
# ═══════════════════════════════════════════════════════════════

def memory_node(state: GlassesState) -> GlassesState:
    lang   = state.get("language", "en")
    target = (state.get("memory_target") or "").strip()

    if not target:
        # No target extracted — ask the user to be more specific
        _no_target = {
            "en": "What object are you looking for? Please say its name.",
            "fr": "Quel objet cherchez-vous ? Dites son nom.",
            "ar": "ما الشيء الذي تبحث عنه؟ قل اسمه.",
            "tn": "شنو الحاجة اللي تحب تلقاها؟ قول اسمها.",
        }
        return {**state, "speak": _no_target.get(lang, _no_target["en"])}

    record = get_last_sighting(target, state.get("user_id") or "")

    if not record:
        speak = t("memory_never_seen", lang, target=target)
        return {**state, "speak": speak}

    # Build relative time string
    time_str = relative_time(record["saved_at"], lang)

    # Try to get a human-readable location
    lat = record.get("gps_lat")
    lng = record.get("gps_lng")
    location_str = None
    if lat is not None and lng is not None:
        try:
            location_str = reverse_geocode(lat, lng)
        except Exception:
            pass

    if location_str:
        speak = t("memory_last_seen", lang,
                  target=target,
                  time=time_str,
                  location=location_str)
    else:
        scene = record.get("scene_description") or ""
        # Build a natural location description from the scene
        if scene:
            location_desc = scene
        else:
            location_desc = {
                "en": "an unknown location",
                "fr": "un endroit inconnu",
                "ar": "مكان غير معروف",
                "tn": "بلاصة ما نعرفهاش",
            }.get(lang, "an unknown location")
        speak = t("memory_last_seen_no_location", lang,
                  target=target,
                  time=time_str,
                  scene=location_desc)

    print(f"[memory] query='{target}' → {time_str}, loc={location_str}")
    return {**state, "speak": speak}


# ═══════════════════════════════════════════════════════════════
# NODE 4g — name_node
# Answers "what is my name?" from the user profile DB.
# ═══════════════════════════════════════════════════════════════

def name_node(state: GlassesState) -> GlassesState:
    from memory_service import get_user_name
    lang = state.get("language", "en")
    name = get_user_name(state.get("user_id") or "")

    _name_responses = {
        "en": {
            "known":   "Your name is {name}.",
            "unknown": "I don't know your name yet. Tell me your name and I will remember it.",
        },
        "fr": {
            "known":   "Votre nom est {name}.",
            "unknown": "Je ne connais pas encore votre nom. Dites-moi votre nom et je m'en souviendrai.",
        },
        "ar": {
            "known":   "اسمك هو {name}.",
            "unknown": "لا أعرف اسمك بعد. أخبرني باسمك وسأتذكره.",
        },
        "tn": {
            "known":   "اسمك هو {name}.",
            "unknown": "ما نعرفش اسمك بعد. قولي اسمك وباش نتذكره.",
        },
    }

    lang_resp = _name_responses.get(lang, _name_responses["en"])
    if name:
        speak = lang_resp["known"].format(name=name)
    else:
        speak = lang_resp["unknown"]

    return {**state, "speak": speak}


# ═══════════════════════════════════════════════════════════════
# NODE 4h — save_location_node
# "Save this location as home" → saves GPS to named_locations DB.
# ═══════════════════════════════════════════════════════════════

def save_location_node(state: GlassesState) -> GlassesState:
    from memory_service import save_named_location
    lang     = state.get("language", "en")
    entities = state.get("entities", [])
    label    = (entities[0] if entities else "home").strip().lower()
    lat      = state.get("user_lat")
    lng      = state.get("user_lng")
    user_id  = state.get("user_id") or ""

    _no_gps = {
        "en": "I need your GPS location to save this place. Please enable location services.",
        "fr": "J'ai besoin de votre position GPS. Activez la localisation.",
        "ar": "أحتاج إلى موقعك GPS لحفظ هذا المكان. يرجى تفعيل خدمات الموقع.",
        "tn": "محتاج موقعك GPS باش نحفظ هذه البلاصة. فعّل خدمة الموقع.",
    }
    _saved = {
        "en": "Done. I saved this location as {label}. Say take me to {label} anytime.",
        "fr": "Fait. J'ai sauvegardé cet endroit comme {label}. Dites emmenez-moi à {label}.",
        "ar": "تم. حفظت هذا المكان كـ {label}. قل خذني إلى {label} في أي وقت.",
        "tn": "صار. حفظت هذه البلاصة كـ {label}. قول روحني لـ {label} وقتاش ما تحب.",
    }
    _already = {
        "en": "You already have '{label}' saved. Say YES to replace it with the current location, or NO to cancel.",
        "fr": "Vous avez déjà '{label}' enregistré. Dites YES pour le remplacer, ou NO pour annuler.",
        "ar": "لديك '{label}' محفوظاً بالفعل. قل YES للاستبدال بالموقع الحالي، أو NO للإلغاء.",
        "tn": "عندك بالفعل '{label}' محفوظ. قول YES باش تبدّله بالموقع الحالي، ولا NO باش توقف.",
    }

    if lat is None or lng is None:
        return {**state, "speak": _no_gps.get(lang, _no_gps["en"])}

    # ── Duplicate check — skip when user already confirmed replacement ──
    if not state.get("_force_replace"):
        try:
            existing = get_named_location(label, user_id)
        except Exception:
            existing = None
        if existing:
            speak = _already.get(lang, _already["en"]).format(label=label)
            print(f"[save_location] duplicate '{label}' — asking to replace")
            return {**state, "speak": speak, "mode": "CONFIRM_REPLACE_LOCATION"}

    try:
        save_named_location(label, lat, lng, user_id)
        speak = _saved.get(lang, _saved["en"]).format(label=label)
        print(f"[save_location] {'replaced' if state.get('_force_replace') else 'saved'} '{label}' @ {lat},{lng}")
    except Exception as e:
        speak = "Sorry, I could not save the location."
        print(f"[save_location] error: {e}")

    return {**state, "speak": speak}


# ═══════════════════════════════════════════════════════════════
# NODE 4i — delete_location_node
# "Delete this location" / "Forget home" → removes from DB.
# ═══════════════════════════════════════════════════════════════

def delete_location_node(state: GlassesState) -> GlassesState:
    from memory_service import delete_named_location, get_named_location
    from memory_service import reverse_geocode, get_all_named_locations
    lang     = state.get("language", "en")
    entities = state.get("entities", [])
    label    = (entities[0] if entities else "").strip().lower()
    lat      = state.get("user_lat")
    lng      = state.get("user_lng")
    user_id  = state.get("user_id") or ""

    _deleted = {
        "en": "Done. I deleted the location {label}.",
        "fr": "Fait. J'ai supprimé l'endroit {label}.",
        "ar": "تم. حذفت المكان {label}.",
        "tn": "صار. مسحت البلاصة {label}.",
    }
    _not_found = {
        "en": "I don't have a saved location called {label}.",
        "fr": "Je n'ai pas d'endroit sauvegardé appelé {label}.",
        "ar": "ليس لدي مكان محفوظ باسم {label}.",
        "tn": "ما عنديش بلاصة محفوظة باسم {label}.",
    }
    _deleted_current = {
        "en": "Done. I deleted the current location.",
        "fr": "Fait. J'ai supprimé l'endroit actuel.",
        "ar": "تم. حذفت الموقع الحالي.",
        "tn": "صار. مسحت البلاصة الحالية.",
    }

    # If no label given, try to find by current GPS
    if not label and lat is not None and lng is not None:
        try:
            rows = get_all_named_locations(user_id)
            best_label = None
            best_dist  = float("inf")
            for row in rows:
                dlat = (row["gps_lat"] - lat) ** 2
                dlng = (row["gps_lng"] - lng) ** 2
                d = (dlat + dlng) ** 0.5
                if d < best_dist:
                    best_dist  = d
                    best_label = row["label"]
            if best_label and best_dist < 0.01:  # ~1 km
                delete_named_location(best_label, user_id)
                return {**state, "speak": _deleted_current.get(lang, _deleted_current["en"])}
        except Exception:
            pass
        return {**state, "speak": _not_found.get(lang, _not_found["en"]).format(label="this location")}

    if not label:
        return {**state, "speak": _not_found.get(lang, _not_found["en"]).format(label="that")}

    deleted = delete_named_location(label, user_id)
    if deleted:
        speak = _deleted.get(lang, _deleted["en"]).format(label=label)
    else:
        speak = _not_found.get(lang, _not_found["en"]).format(label=label)

    return {**state, "speak": speak}


# ═══════════════════════════════════════════════════════════════
# NODE 4j — save_object_node
# "Save this as my keys" → opens camera so user can point at object.
# Actual DB save happens via POST /save_personal_object after the
# user confirms the VLM description in Flutter.
# ═══════════════════════════════════════════════════════════════

def save_object_node(state: GlassesState) -> GlassesState:
    lang     = state.get("language", "en")
    entities = state.get("entities", [])
    name     = (entities[0] if entities else "object").strip()

    _speak = {
        "en": f"Opening camera. Point it at {name} and tap to capture. I'll describe what I see and ask you to confirm.",
        "fr": f"Ouverture de la caméra. Pointez-la vers {name} et appuyez pour capturer. Je décrirai ce que je vois.",
        "ar": f"جاري فتح الكاميرا. وجّهها نحو {name} واضغط للتقاط الصورة. سأصف ما أراه.",
        "tn": f"نفتح الكاميرا. وجّهها ناحية {name} وانقر باش نصوّر. باش نوصفلك شنو نشوف.",
    }
    return {**state,
            "speak": _speak.get(lang, _speak["en"]),
            "mode": "SAVE_OBJECT"}


# ═══════════════════════════════════════════════════════════════
# NODE 4k — save_person_node
# "This is my friend Ahmed" → opens camera to capture face.
# Actual DB save happens via POST /save_person after confirmation.
# ═══════════════════════════════════════════════════════════════

def save_person_node(state: GlassesState) -> GlassesState:
    lang     = state.get("language", "en")
    entities = state.get("entities", [])
    name     = (entities[0] if entities else "person").strip()
    rel      = (entities[1] if len(entities) > 1 else "person").strip()

    # __SELF__ sentinel — resolve user's own saved name from DB
    if name == "__SELF__" or rel in ("self", "me", "myself"):
        rel = "self"
        try:
            from memory_service import get_user_name
            _stored = get_user_name(state.get("user_id") or "")
            name = _stored if _stored else "you"
        except Exception:
            name = "you"

    _speak = {
        "en": (f"Opening camera to save your face, {name}. "
               f"Point the front camera at your face and tap to capture.")
              if rel == "self" else
              f"Opening camera to save {name}. Point it at their face and tap to capture.",
        "fr": (f"Ouverture de la caméra pour enregistrer votre visage, {name}. "
               f"Pointez la caméra frontale vers votre visage et appuyez.")
              if rel == "self" else
              f"Ouverture de la caméra pour sauvegarder {name}. Pointez vers leur visage et appuyez.",
        "ar": (f"جاري فتح الكاميرا لحفظ وجهك يا {name}. "
               f"وجّه الكاميرا الأمامية نحو وجهك واضغط للتقاط.")
              if rel == "self" else
              f"جاري فتح الكاميرا لحفظ {name}. وجّهها نحو وجهه واضغط للتقاط.",
        "tn": (f"نفتح الكاميرا باش نحفظ وجهك يا {name}. "
               f"وجّه الكاميرا الأمامية نحو وجهك وانقر باش تصوّر.")
              if rel == "self" else
              f"نفتح الكاميرا باش نحفظ {name}. وجّهها لوجهه وانقر باش تصوّر.",
    }
    return {**state,
            "speak": _speak.get(lang, _speak["en"]),
            "mode": "SAVE_PERSON",
            "entities": [name, rel]}


# ═══════════════════════════════════════════════════════════════
# NODE 5 — action_speak
# ═══════════════════════════════════════════════════════════════

def action_speak(state: GlassesState, *, action: ActionAgent) -> GlassesState:
    speak     = state.get("speak", "")
    interrupt = state.get("interrupt", False)
    language  = state.get("language", "en")

    # ── "I can see you" injection for non-describe nodes ────────
    # describe() already appends person sentences for DESCRIBE mode.
    # For every other mode (navigate, find_object, danger, etc.) we
    # inject it here so the user hears it regardless of what they asked.
    _mode = (state.get("mode") or "").upper()
    if _mode not in {"DESCRIBE", "IDLE", ""}:
        _scene = state.get("scene") or {}
        for _ip in (_scene.get("identified_persons") or []):
            if not _ip.get("match") or _ip.get("confidence") == "low":
                continue
            _rel = (_ip.get("relationship") or "").strip().lower()
            if _rel not in {"self", "me", "myself"}:
                continue
            _name = _ip["match"]
            _greeting = {
                "en": f"I can see you, {_name}.",
                "fr": f"Je vous vois, {_name}.",
                "ar": f"أراك يا {_name}.",
                "tn": f"نشوفك يا {_name}.",
            }.get(language, f"I can see you, {_name}.")
            speak = (_greeting + " " + speak).strip() if speak else _greeting
            break  # only announce once even if multiple matches

    if speak:
        if interrupt:
            action.speak_danger(speak)
        else:
            action.speak_normal(speak, lang=language)
        tag = "🚨 " if interrupt else ""
        print(f"[action_speak] {tag}({language}) {speak}")
    return state


# ═══════════════════════════════════════════════════════════════
# GRAPH BUILDER
# ═══════════════════════════════════════════════════════════════

def build_graph(api_key: str, google_api_key: str = "",
                emotion_agent=None):
    perception_agent = PerceptionAgent(
        api_key=api_key, mode="external",
        primary_model=VLM_MODEL_VISION,
        fallback_model=VLM_MODEL_FALLBACK,
        extra_fallbacks=VLM_MODEL_EXTRA_FALLBACKS,
        google_api_key=google_api_key,
        min_confirmations=VISION_MIN_CONFIRMATIONS,
        history_size=VISION_MAX_HISTORY,
    )
    action_agent   = ActionAgent()
    navigate_agent = NavigateAgent()

    def _perception(s):   return perception_node(s, perception=perception_agent,
                                                  emotion=emotion_agent)
    def _action_speak(s): return action_speak(s, action=action_agent)
    def _navigate(s):     return navigate(s, navigator=navigate_agent)

    g = StateGraph(GlassesState)
    g.add_node("perception",   _perception)
    g.add_node("danger_node",  danger_node)
    g.add_node("confirm_node", confirm_node)
    g.add_node("clarify_node", clarify_node)
    g.add_node("route_intent", route_intent)
    g.add_node("find_object",  find_object)
    g.add_node("describe",     describe)
    g.add_node("navigate",     _navigate)
    g.add_node("query",             query)
    g.add_node("read_handwriting",  read_handwriting_node)
    g.add_node("memory_node",       memory_node)
    g.add_node("name_node",         name_node)
    g.add_node("save_location_node",   save_location_node)
    g.add_node("delete_location_node", delete_location_node)
    g.add_node("save_object_node",     save_object_node)
    g.add_node("save_person_node",     save_person_node)
    g.add_node("action_speak",         _action_speak)

    g.set_entry_point("perception")

    g.add_conditional_edges("perception", after_perception, {
        "danger_node":  "danger_node",
        "confirm_node": "confirm_node",
        "clarify_node": "clarify_node",
        "route_intent": "route_intent",
    })

    g.add_edge("danger_node",  "action_speak")
    g.add_edge("confirm_node", "action_speak")
    g.add_edge("clarify_node", "action_speak")

    g.add_conditional_edges("route_intent", after_route, {
        "find_object":         "find_object",
        "describe":            "describe",
        "navigate":            "navigate",
        "query":               "query",
        "read_handwriting":    "read_handwriting",
        "memory_node":         "memory_node",
        "name_node":           "name_node",
        "save_location_node":  "save_location_node",
        "delete_location_node": "delete_location_node",
        "save_object_node":    "save_object_node",
        "save_person_node":    "save_person_node",
        "action_speak":        "action_speak",
    })

    for leaf in ("find_object", "describe", "navigate", "query",
                  "read_handwriting", "memory_node", "name_node",
                  "save_location_node", "delete_location_node",
                  "save_object_node", "save_person_node"):
        g.add_edge(leaf, "action_speak")
    g.add_edge("action_speak", END)

    return g.compile(), action_agent, perception_agent